In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.display import display
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA, KernelPCA
from sklearn.manifold import TSNE
from sklearn.manifold import Isomap
import umap
from sklearn.manifold import trustworthiness
from sklearn.model_selection import GridSearchCV

In [2]:
data = pd.read_pickle('data_mod.pkl')
data.head()

,k1,k2,k3,k4,k5,k6,k7,k9,k10,k11,k12,k13,k14,k15,k16,k17,k18,k19,k20
0,0.403809,0.503518,0.548820,0.328302,0.330954,0.475458,0.833823,0.529053,0.330879,0.414133,0.451272,0.309298,0.359411,0.340312,0.459953,1.000000,0.554562,0.497247,0.479035
1,0.591695,0.653597,0.632007,0.763404,0.169329,0.543158,0.421875,0.903975,0.333300,0.515462,0.471764,0.330484,0.592674,0.566433,0.490934,1.000000,0.678800,0.510526,0.458055
2,0.300968,0.462057,0.341906,0.000000,0.379270,0.893999,1.000000,0.511229,0.284299,0.173041,0.502503,0.083725,0.220906,0.402367,1.000000,0.558105,0.000000,0.371303,0.399927
3,1.000000,1.000000,1.000000,0.902599,0.126387,0.311175,0.433346,0.999822,0.607228,0.489965,0.564472,1.000000,1.000000,0.942774,0.418881,0.546973,0.854628,1.000000,1.000000
4,0.555295,0.464936,0.620328,0.709942,0.235475,1.000000,0.927524,0.752390,0.374004,0.243528,0.407338,0.231825,0.403838,0.317202,0.420597,0.496557,0.516877,0.414231,0.426759

In [14]:
def scorer_func(estimator, data):
    return trustworthiness(data, estimator.transform(data), n_neighbors = 5)

In [15]:
kpca = KernelPCA(kernel = 'rbf', n_components = 7)
grid_search_kernelpca = GridSearchCV(estimator = kpca, param_grid = {'gamma': [0.001, 0.01, 0.05, 0.1, 0.5, 1.0]}, scoring = scorer_func, cv = 5)

In [21]:
grid_search_kernelpca.fit(data)
cv_df = pd.DataFrame(grid_search_kernelpca.cv_results_)
print(grid_search_kernelpca.best_params_, '\n', grid_search_kernelpca.best_score_)
cv_df[['param_gamma', 'mean_test_score','std_test_score', 'rank_test_score']]

{'gamma': 0.001}
 0.988126718586767

   param_gamma  mean_test_score  std_test_score  rank_test_score
0        0.001         0.988127        0.001533                1
1        0.010         0.987988        0.001512                2
2        0.050         0.986778        0.001081                3
3        0.100         0.985073        0.000791                4
4        0.500         0.981267        0.001151                5
5        1.000         0.976410        0.001424                6